const storeProduct =[
{
    name_prefix:'Васильковый хаплохромис',
    full_name:'Sciaenochromis fryeri',
    size:'>7см',
    description:'',
    images:'https://aquavip.by/image/cache/catalog/tovary/rybki/cihlidy/haplohromis/Electric-Blue-Cichlid-2048x1366-2048x1366_moytop.webp',
    prices:'10-13 BYN',
},
{
    name_prefix:'Снежный принц',
    full_name:'Pseudotropheus socolofi albino',
    size:'3см',
    description:'',
    images:'https://aqualine.info/userfls/shop/large/7994_snezhnyy-prints-psevdotrofe.jpg',
    prices:'2.5 BYN',
},
{
    name_prefix:'Анциструс',
    full_name:'Анциструс золотой',
    size:'до 15 см',
    description:'',
    images:'https://fanfishka.ru/uploads/posts/2019-10/1570284725_05.jpg',
    prices:'12 BYN',
},
{
    name_prefix:'Анциструс',
    full_name:'Анциструс простой',
    size:'до 15 см',
    description:'',
    images:'https://s6.stc.all.kpcdn.net/family/wp-content/uploads/2021/12/ancistrus-2-960x540.jpg',
    prices:'10 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио телесный',
    size:'от 1,7 см',
    description:'',
    images:'https://www.aqvium.ru/images/fish-new/cyprinidae/02.Danio-rerio/022.jpg',
    prices:'0.3 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио рерио',
    size:'от 1,7 см',
    description:'', 
    images:'https://blog.tetra.net/ru/ru/wp-content/uploads/2018/11/danio-rerio-1.jpg',
    prices:'0.5 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио ГЛО  супер красные в белую (полоску,точку)',
    size:'от 1,7 см',
    description:'',
    images:'https://blog.tetra.net/ru/ru/wp-content/uploads/2018/10/danio-rerio-rozovyj.jpg',
    prices:'0.7 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио ГЛО красные в синию (полоску,точку)',
    size:'от 1,7 см',
    description:'',
    images:'https://akvamir72.ru/wa-data/public/shop/products/62/17/1762/images/2612/2612.580@2x.jpg', 
    prices:'0.7 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио ГЛО синие',
    size:'от 1,7 см',
    description:'',
    images:'https://timaqua.ru/images/product_images/popup_images/tovar/fish/danio_blue_xl.jpg',
    prices:'0.7 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио Гло салатовые и изумрудные',
    size:'от 1,7 см',
    description:'',
    images:'https://mag.ribdom.ru/images/detailed/21/55d0e103ef7811ed8b9bfa163e0e1e42_02e043ae905011ee9fab005056bc8b10.jpg',
    prices:'0.7 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио жемчужный',
    size:'от 1,7 см',
    description:'',
    images:'https://fanfishka.ru/uploads/posts/2020-04/1587613600_awuo3frzua8.jpg',
    prices:'0.8 BYN',
},
{
    name_prefix:'Креветка',
    full_name:' Креветка Неокаридина оранжевая сакура',
    size:'3 см',
    description:'',
    images:'https://garfield.by/upload/iblock/d47/59uce0td2y83f1aey4am4ka3cd3ouxhx/47e1920941448e7201f8314d3136.jpg',
    prices:'1.6 BYN',
},
{
    name_prefix:'Тернеция',
    full_name:'Тернеция ГЛО жёлтая',
    size:'0,5 см',
    description:'',
    images:'https://shop-cdn1-2.vigbo.tech/shops/183385/products/20997180/images/2-797cdbaa377f485a43adf6a61a93e522.png',
    prices:'0.5 BYN',
},
{
    name_prefix:'Тернеция',
    full_name:'Тернеция ГЛО розовая',
    size:'0,5 см',
    description:'',
    images:'https://blog.tetra.net/ru/ru/wp-content/uploads/2021/05/terneciya-krasnaya.jpg',
    prices:'0.5 BYN',
},
{
    name_prefix:'Тернеция',
    full_name:'Тернеция ГЛО суперкрасная',
    size:'0,5 см',
    description:'',
    images:'https://mag.ribdom.ru/images/detailed/22/15326.jpg',
    prices:'0.5 BYN',
},
{
    name_prefix:'Тернеция',
    full_name:'Тернеция телесная',
    size:'0,5 см',
    description:'',
    images:'https://zviazda.by/sites/default/files/img_2309.jpg',
    prices:'0.5 BYN',
},
{
    name_prefix:'Попугай',
    full_name:'Попугай тигровый сапфировый ',
    size:'2-4 см',
    description:'',
    images:'https://garfield.by/upload/iblock/3dc/3z04msmd8svjf2ev9263no8ejy2cqti3/noZ1MraBMm8Dl8BpRSDl_pKRNmnXlzJpsPI2aQOXwGnDlT5rw5MyKw.jpg',
    prices:'1 - 2 BYN',
},
{
    name_prefix:'Гуппи',
    full_name:' Гуппи Эндлера Скай Блю',
    size:'2-3 см',
    description:'',
    images:'https://aquahvost.by/d/gurry-endlera-sky-blue.jpg',
    prices:'1.5 BYN',
},
{
    name_prefix:'Гуппи',
    full_name:'Гуппи Дамбо мозаика',
    size:'3 см',
    description:'',
    images:'https://avatars.mds.yandex.net/i?id=94d8883997f2ce5c7019247d2222d2c836a1c5d1-9095279-images-thumbs&n=13',
    prices:'2.2BYN',
},
{
    name_prefix:'Гуппи',
    full_name:'Гуппи Дамбо Драгон Хэд',
    size:'3 см',
    description:'',
    images:'https://biohob.by/assets/cache/images/catalog/zhivotnye/fish/guppi-golova-drakona/14-poecilia-reticulata-guppy-male-dragon-head-380x390-537.jpg',
    prices:'2.2 BYN',
},
{
    name_prefix:'Гуппи',
    full_name:'Гуппи кои',
    size:'4,5 см',
    description:'',
    images:'https://alexaquashop.ru/images/catalog/item/16551470651174_alexaquashop.ru-guppi-koi.jpg',
    prices:'2.2 BYN',
},
{
    name_prefix:'Гурами',
    full_name:'Гурами мраморный с 2-мя точками',
    size:'3 см',
    description:'',
    images:'https://biohob.by/assets/cache/images/catalog/zhivotnye/fish/gurami-mramornyj/udeijwktzy-380x390-537.jpg',
    prices:'0.8 BYN',
},
{
    name_prefix:'Гурами',
    full_name:'Гурами глубокий мрамор',
    size:'3 см',
    description:'',  
    images:'https://www.aqvium.ru/templates/yootheme/cache/12-1.opaline-gourami-15a67f02.jpeg',
    prices:'0.8 BYN',
},
{
    name_prefix:'Скалярия',
    full_name:'Скалярия мраморная',
    size:'1 см',
    description:'',
    images:'https://blog.tetra.net/ru/ru/wp-content/uploads/2021/05/mramornaya-skalyariya-vneshnij-vid.jpg',
    prices:'1.6 BYN ',
},
{
    name_prefix:'Скалярия',
    full_name:'Скалярия кои красный дьявол',
    size:'1 см',
    description:'',
    images:'https://blog.tetra.net/ru/ru/wp-content/uploads/2022/11/skalyariya-krasnyj-dyavol.jpg',
    prices:'2 BYN',
},
{
    name_prefix:'Скалярия',
    full_name:'Скалярия фантом красный',
    size:'0,5 см',
    description:'',
    images:'https://fanfishka.ru/uploads/posts/2020-05/1590327750_1.jpg',
    prices:'1.5 BYN',
},
{
    name_prefix:'Скалярия',
    full_name:'Скалярия фантом светлый',
    size:'0,5 см',
    description:'',
    images:'https://biohob.by/assets/cache/images/catalog/zhivotnye/fish/skalyariya-svetlyj-fantom/12807.750-380x390-537.jpg',
    prices:'1.5 BYN',
},
{
    name_prefix:'Ампулярия',
    full_name:'Ампулярия ореховая с жёлтой ногой',
    size:'1 см',
    description:'',
    images:'https://aqua-tver.su/sites/default/files/product/Ulitka-ampulyaria-pr.jpg',
    prices:'0.6 BYN',
},
{
    name_prefix:'Барбус',
    full_name:'Барбус суматранский',
    size:'0,5 / 2 см',
    description:'',
    images:'https://fanfishka.ru/uploads/posts/2015-04/1429902425_1.jpg',
    prices:'0.8 / 1 BYN',
},
{
    name_prefix:'Барбус',
    full_name:'Барбус красный ГЛО с чёрной полосой',
    size:'1 см',
    description:'',
    images:'https://akvamir72.ru/wa-data/public/shop/products/51/17/1751/images/2621/2621.970.jpg',
    prices:'1.6BYN',
},
{
    name_prefix:'Барбус',
    full_name:'Барбус одесский',
    size:'1 см',
    description:'',
    images:'https://akvafan.ru/sites/files/images/2019/alyy_barbus.jpg',
    prices:'1.6BYN',
},
]